---
-  name: tasks file for Variables
   hosts: all
   become: true
   # Variables used in this playbook
   vars:
     ucd_group: "JJTechGroup2"
     ucd_user: "JJTechUser2"
   tasks:
      - name: Create UCD group
        become: true
        group:
          name: "{{ ucd_group }}"
          system: true

      - name: Create UCD user
        become: true
        user:
          name: "{{ ucd_user }}"
          group: "{{ ucd_group }}"
          system: true
